### ISSUE TITLE
Add support for 1Password vaults

### ISSUE THREAD

**Issue by sergeylukin** [SpectralOps/teller#10]
`tlr` is absolutely amazing!
It would be awesome to be able to use teller with [1Password](https://1password.com/) vaults.
There is 1Password CLI: https://support.1password.com/command-line-getting-started/
WDYT?

**Comment by jondot** [comment]
sounds good, we're aiming to add the new 1password production offering they announced a couple weeks ago (which makes them into a production vault product too)

**Comment by kaplanelad** [comment]
@jondot, 1password provider was added #49. 
we can close this issue
