### ISSUE TITLE
could not load all variables from the given existing providers 

### ISSUE THREAD

**Issue by oxrishang** [SpectralOps/teller#113]
## Expected Behavior
Load numbers too in env as string value

## Current Behavior
getting error: FATA[0000] could not load all variables from the given existing providers  error="json: cannot unmarshal number into Go value of type string"

## Possible Solution
If we can convert number into string it will be good so load number base secret values

## Steps to Reproduce

1. Get teller v1.5.1
2. Create a secret with having value as a number in aws secrets manager
3. load the secrets using `teller run`

## Context
I have some secrets in number format in aws secrets manager, wich i want to load as `teller run -- node app.js`

## Specifications
  - Version: `[v1.5.1]`
  - Platform:  Ubuntu 22.04

**Comment by kaplanelad** [comment]
Hey @oxrishang, 
Thanks for reported us this issue, we will check this issue

**Comment by kaplanelad** [comment]
@oxrishang, version 1.5.2 includes the bug fix that you reported.
