### ISSUE TITLE
Azure KeyVault integration 

### ISSUE THREAD

**Issue by mpender** [SpectralOps/teller#12]
Could we get azure key vault integration? 
https://docs.microsoft.com/en-us/rest/api/keyvault/getsecret/getsecret

**Comment by jondot** [comment]
It should already exist,
https://github.com/SpectralOps/teller/blob/master/pkg/providers/azure_keyvault.go

Did you find anything missing or a different kind of integration with Azure KV?

**Comment by mpender** [comment]
no, thats perfect. il try it out. thanks

**Comment by jondot** [comment]
great. please do let me know how that works for you and if there's anything to improve
