### ISSUE TITLE
Wrong documentation for .env code sample on the tlr.dev

### ISSUE THREAD

**Issue by look4regev** [SpectralOps/teller#122]
In https://tlr.dev/ under the `.env` code sample, it should be `dotenv` instead of `aws_secretsmanager`:
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/4006829/179422800-93c7a8a8-c689-42dc-8051-30a9d59ff99c.png">
The source code for tlr.dev is closed right? Consider publishing it so this could have been a quick PR instead of an issue :)

**Comment by kaplanelad** [comment]
Hey @look4regev, 
Yes, the source code of tlr.dev is closed for now, we are working on a new website and planning move it to the public.
We will fix the documentation. Thanks

**Comment by kaplanelad** [comment]
@look4regev, I'm closing this issue, and during it is not related to this repo. we will fix it on the new Teller website

Thanks for letting us know
