### ISSUE TITLE
Information request : Obfuscation functionality

### ISSUE THREAD

**Issue by advissor** [SpectralOps/teller#13]
Taking a look into docs, there is an secret obfuscation possibility 

1) Does it do secret obfuscation based on only known secrets?
2) Can it be used for any data like history, where someone might accidentally paste a password or etc in clear text?
3)  teller --in dirty.csv --out clean.csv
On MacOS 

`➜  teller-test teller version  
Teller 1.0.0
Revision 684b421ad8f96acb3de9bcb0f75339d5b4912030, date: 2021-04-14T12:43:07Z
➜  teller-test teller --in file-t.txt --out clean.txt    
teller: error: unknown flag --in`

**Comment by jondot** [comment]
Hi, I think basically it does all that you mentioned.

Just to clarify, when you say "secret obfuscation based on only known secrets" what do you mean? can you give an example?

**Comment by advissor** [comment]
1) @jondot I mean, that I have an arbitrary and no formatted file. Where for some reason, somebody in output left the secret keys or something like this

Because for you to get  understand that in this random file there is a secret : 
- the secret pattern is known 
-  either some  regexp / pattern recognition finds it

This is what I mean by the "known" secrets

2) There is still that nasty error with missing flag "--in"

**Comment by jondot** [comment]
For 1 + 2, yes, known only. If you need a solution for unknown secrets, that's what we do at SpectralOps (feel free to shoot me an email dotan@spectralops.io)

for 3 - now I understand, thanks I'll check that out.

**Comment by jondot** [comment]
For the `--in` parameter -- I just missed `redact`, it should be `teller redact --in ...` (I updated in docs), thanks!
