### ISSUE TITLE
Question: hashicorp vault auth

### ISSUE THREAD

**Issue by NikitaGl** [SpectralOps/teller#19]
Hi. I've recently discovered your project and fascinated with capabilities it provides. However, there is some things that are not completely clear for me. As you might guessed from a title, I am figuring out how does Teller authenticates against Hashicorp Vault. 
Readme says: 
>  if for example you connect to your organization's Hashicorp Vault, we assume you already have a secure way to do that, which is "blessed" by the organization.

Does this mean that Teller inherits all auth methods Vault provides, or it is up to me how to acquire and feed Teller with `VAULT_TOKEN`? I am specifically interested in AWS Auth method, since Teller might perfectly fit to my ECS runtime as secret injection tool.

**Comment by jondot** [comment]
Basically what Teller starts with -- is using the recommended way to auth, and not trying to invent a new way. In this case, when we look at the official client for Hashicorp Vault, these are the parameters that participate in authentication [here](https://github.com/hashicorp/vault/blob/api/v1.0.4/api/client.go#L28-L42).

So we call the client default authentication configuration logic, and it pulls what it needs from the environment.

If/when we bump into a new, more involved way to authenticate, of course we will accept PRs for it and if needed work on it ourselves -- but we always prefer to just use what the provider client does natively.

**Comment by NikitaGl** [comment]
Understood. So in case with Vault Teller adopts it's default logic of token authentication. That's a bummer for me :)
Then, I guess I'm going to open  a feature request for supporting AWS auth in Vault, since I'm not a big expert in Go.

**Comment by jondot** [comment]
Yea, I mean, if it's standard in your eyes -- just try to specify here exactly how you connect. I can take a look and see if it works already with Vault and prepare an implementation.

**Comment by NikitaGl** [comment]
Understood. 
Speaking about Vault cli, authenticating with AWS Auth there happens through passing special commandline flags:
`vault login -method=aws header_value=vault.example.com role=myrole`
Vault Agent uses another approach where you are configuring auto-auth through HCL config.

**Comment by jondot** [comment]
Got it, so as I analyze this (please correct me if wrong):

1. We know that Vault has many ways to authenticate (AWS, github, etc.), and the end result of that, is a timed token (which you use to access Vault)
2. For convenience and automation, Hashicorp offers Vault Agent, which takes care of renewing and generating tokens for you in a continuous manner

It seems, that these kind of complexities are Hashicorp-managed/maintained and the best thing for Teller would be to remain on the "common language" which is the token.

So, for example by using https://www.vaultproject.io/docs/agent/autoauth/sinks/file you could get your token to be used for Teller (after you used Vault Agent to authenticate in any way you prefer).

Would that work for you?

**Comment by NikitaGl** [comment]
That is exactly what I am planning to do for now :) 
I was hoping to avoid additional steps, especially what involves storing access tokens in a plain file. But I guess there is zero alternative just for now ¯\_(ツ)_/¯

**Comment by jondot** [comment]
I believe the best way would be somehow to use Vault agent to populate the token as an environment variable, it is odd that Hashicorp didn't provide any such way.

Please let me know how it goes for you meanwhile

**Comment by iniinikoski** [comment]
Hi,

I've been also pondering this, the role of Teller and Vault...

Currently I'm considering that with AWS ECS, we'd do Vault Agent directly as a sidecar there - but for local development - we'd use Teller as a "helper tool" - we'd just first authenticate (with OIDC for example) - and continue with Teller from there. Maybe. Need to poke this a bit moer...

**Comment by jgrumboe** [comment]
@NikitaGl 
Did you get further with your setup?
Could it look like running the vault agent with AWS auth as a sidecar in ECS and using teller to fetch credentials through vault-agent sidecar? This way you would just need a fake-token for teller against vault-agent and vault-agent would do the AWS auth against real vault server - AFAIK.

**Comment by NikitaGl** [comment]
A actually ended up authenticating through AWS with Vault Agent Auto-Auth, getting short-living token and using it with secret injection tool. It may seem more janky because I'm placing both binaries in app container image, but it covered all my requests.

I am actually forgot about this thread and since I had received my answers and implemented working solution this topic can be closed.
