### ISSUE TITLE
Teller env output multiple formats

### ISSUE THREAD

**Issue by vongohren** [SpectralOps/teller#20]
Hi guys! I really like this tool, I just have one concern and that is that it would be great with multiple formats for `teller env`
Some flag to be able to set what shall be outputed.

F.ex, google cloud functions have a way to set envs via file, but they expect a yml file.
You can set via an array, but again, this format only outputs as an .env file.

Has there been any thoughts around this or exist some undocumented code?

Some documentation, search for `--env-vars-file` in https://cloud.google.com/sdk/gcloud/reference/functions/deploy

**Comment by jondot** [comment]
Awesome,
Right now we export ENV and shell sourcing, but we'll be happy to add this format as well.
What would be a perfect way for you to specify the format in terms of command line ergonomics?

**Comment by vongohren** [comment]
Great! I would love to help but I'm not proficient in golang. But I got the ideas from doppler https://docs.doppler.com/docs/accessing-secrets#downloading

So maybe a simple format flag after env is enough?

**Comment by jondot** [comment]
yep, that looks great. I'll write down a short spec and we will implement it,  thanks for the suggestion!

**Comment by vongohren** [comment]
Sounds good! Looking forward to the release!

**Comment by jondot** [comment]
We now should have these formats, from this PR: https://github.com/SpectralOps/teller/pull/22 

* env (`teller env`)
* dotenv (`teller env > .env`)
* shell sourcing (`teller sh`)
* YAML, for google and others (`teller yaml`)
* JSON, general purpose (`teller json`)

**Comment by vongohren** [comment]
@jondot great stuff! Not on the top of my mind no!

**Comment by jondot** [comment]
Perfect, i'll move forward to cut a version. Thanks for your ideas!

**Comment by jondot** [comment]
You can now take v1.2.0 for a spin, see if the new formats work for you :)

**Comment by vongohren** [comment]
@jondot great thanks will check tomorrow!

**Comment by vongohren** [comment]
Sorry, tomorrow became today, but looks good. Closing this now
