### ISSUE TITLE
What is the best way to manage environments?

### ISSUE THREAD

**Issue by vongohren** [SpectralOps/teller#21]
I have not found any where I can set environment via cli flag, but I can use seperate files.
How are you using this today?
Or what is your best practise suggstion on this problem?

**Comment by jondot** [comment]
Hi Snow,
We primarily use 2 methods:

1. A single file, where each environment is a parameter ([https://github.com/SpectralOps/teller#white_check_mark-prompts-and-options](see prompts and options), where you can populate one with an environment variable `env:STAGE` and `STAGE=dev teller ...`
2. Keep a config file per environment, similar to what you would do with `.env` file (`.env.example`, `.env.production`, etc.) -- but with teller none of configuration file contain any sensitive information (as opposed to `.env`).

The best practice really depends on the size of your team and how you prefer to work. I imagine if the team is small, and the use cases are not many, a single file would be great. If the team is large, or maybe you're enabling other teams -- keeping a file per environment would be better, and this way you can "distribute" your teller files per use case in a central way.

Does that make sense?

**Comment by vongohren** [comment]
@jondot thanks or informing! Yeah it all makes sense!
Would it make sense to add some best practices doc to this repo? I can add it if we agree on something.

Btw, where did you get the nicknam Snow from :P?

**Comment by jondot** [comment]
Yes, sure it definitely makes sense to add a best-practices section, I would love it.

Found your name on your Github profile README, was simple to find and well made 😄

**Comment by vongohren** [comment]
Ah, I tried to remember where I had put that nickname :P But that makes sense! Thanks.

Here is also a first PR of best practises: https://github.com/SpectralOps/teller/pull/23

**Comment by vongohren** [comment]
Should we close this as we have merged something?

**Comment by lreuven** [comment]
@vongohren sorry for the long delay, 
yes & Thanks for contributing.
