### ISSUE TITLE
Question: How exactly do I use?

### ISSUE THREAD

**Issue by arukaen** [SpectralOps/teller#27]
Hello, I stumbled upon this project while looking for a way to sync my secrets from AWS Secrets Manager to my application server. Originally we are using dotenv (.env) with nodejs to set the secrets for the app. We're looking to move to AWS Secrets Manger to host the secrets and then import them into the application server into a dotenv file. How can I achieve this with teller?

**Comment by jondot** [comment]
Hi @arukaen, Teller actually make .env redundant, and your environment cleaner (you won't have files with secrets sprawling around). Just configure your secret providers as you wish (in your case Secrets Manager) and then run your server:

```
$ teller run bin/your-server
```

This command fetches the relevant secrets and injects them into `bin/your-server`'s environment, essentially doing what `.env` is doing behind the scenes.

If you would still like to avoid changing your code, you can use Teller as an intermediary, so the process would be:

1. Run Teller and export a `.env` file
2. Run your server and have it pick up the generated file

```
$ teller env > .env
$ bin/your-server
```

**Comment by lreuven** [comment]
@arukaen can we close this one?
