### ISSUE TITLE
Add support for lastpas

### ISSUE THREAD

**Issue by artis3n** [SpectralOps/teller#3]
Would be neat to support passwords and other secrets stored in password managers via this tool, such as https://github.com/lastpass/lastpass-cli .

**Comment by jondot** [comment]
Good idea. I'm assuming there is some case where development-related secrets are pulled from Lastpass (in the sense that it's used also for development purposes and not just as a personal thing).

I'm going to label it appropriately and we'll built a provider.

Thanks!

**Comment by artis3n** [comment]
Yeah - for development/local environments where secrets may need to be invoked.

**Comment by schiederme** [comment]
Is it possible to integrate the new Lastpass Secret Managment too?

**Comment by jondot** [comment]
@schiederme yes, that is on the roadmap as well

**Comment by kaplanelad** [comment]
Hey, @artis3n I have implemented LastPass into teller via an HTTP request. 
The option to use CLI is going to handle issue #44  for multiple providers

**Comment by kaplanelad** [comment]
LastPass was added.
