### ISSUE TITLE
Forkert vægt på varer giver problemer med fragt

### ISSUE THREAD

**Issue by rikkeloekke** [SpectralOps/teller#38]
Indenfor ca. en uge har vi modtaget i omegnen af 7-10 pakker retur fra Postnord, der skulle sendes til Brasilien. Grunden til at pakkerne sendes retur er fordi kunden har kunne vælge Postnord varebrev, hvor max vægt er 2 kg., men hvor ordren i virkeligheden vejer langt mere. Synderen er forkert vægtangivelse på LP'er - ofte bokse.

Her er eksempler (hvor jeg dog har været inde og rette vægten): 
https://imusic.dk/music/0603497844531/joni-mitchell-2021-the-reprise-albums-1968-1971-lp (oprindeligt stod vægten til det halve)
https://imusic.dk/music/0602435652375/george-harrison-2021-all-things-must-pass-50th-anniversary-lp
https://imusic.dk/music/4988031396896/thin-lizzy-2020-rock-legends-cd (nu udgået).

Det er naturligvis vigtigt at kunderne vælger den rigtige type forsendelse fra starten, så vi ikke skal betale for retur- og/eller ekstra fragt.

**Comment by jondot** [comment]
looks like wrong place :)
