### ISSUE TITLE
When doing `Put` for dotenv provider, an error is returned if a target file doesn't exist

### ISSUE THREAD

**Issue by pkosiec** [SpectralOps/teller#54]
Hi,

Very cool project! I would be interested to use it as Go API for accessing different secret storage backends (Delegated storage feature for https://github.com/capactio/capact open source project), as you prepared great abstractions.

Anyway, while playing around with Teller Go API, I noticed the following behavior for `dotenv` Provider. When doing `Put`, it returns an error when a given file doesn't exist.

I would love to prepare a pull request to fix such issue for `dotenv` provider. In fact, I have the code ready, but I want to confirm first the expected behavior.

## Expected behavior

I would expect that the `Put` method is doing upsert (create or update) operation, like `PUT` in REST API. By reading the code, this is how I believe the `vault`, `heroku` and `etcd` providers work.

## Minimal example to reproduce

```go
package main

import (
	tellerpkg "github.com/spectralops/teller/pkg"
	"github.com/spectralops/teller/pkg/core"
	"log"
)

func main() {
	providers := tellerpkg.BuiltinProviders{}
	provider, err := providers.GetProvider("dotenv")
	if err != nil {
		panic(err)
	}

	key := core.KeyPath{
		Path:  "/tmp/foo.env",
		Field: "data",
	}

	val := `{"key": "true"}`
	err = provider.Put(key, val)
	if err != nil {
		panic(err) // it will panic here
	}

	// Get
	entry, err := provider.Get(key)
	if err != nil {
		panic(err)
	}

	log.Printf("%+v\n", entry)
}
```

Result:

```
panic: open /tmp/foo.env: no such file or directory
```

**Comment by jondot** [comment]
Hi @pkosiec `capact` look cool!
I think what you're suggesting (upsert semantics) is perfectly fine -- happy to accept your PR

**Comment by pkosiec** [comment]
Thank you @jondot! I've just created a PR (#55). Please let me know if I should change anything. Cheers!
