### ISSUE TITLE
Ability to delete secrets

### ISSUE THREAD

**Issue by pkosiec** [SpectralOps/teller#57]
Hello again,

Teller already supports:
- `Put` (as create+update; both for single and multiple values)
- `Get` (get/list) for the providers
- copying (syncing) all secrets from one provider to another one

Did you also think about supporting `Delete`? It could be a simple `teller delete` command. What I'm thinking is extending the `Provider` interface:

```go
type Provider interface {
	// (...)

        Delete(p KeyPath) error
        DeleteMapping(p KeyPath) // probably this would be also useful
}
```

In a result, Teller would support the full lifecycle of secret management, which could be extremely useful.

We at [Capact](https://github.com/capactio/capact) would be very interested in this feature 🙂 And, we would love to contribute - Initially, in next few days, I could prepare such `Delete` functionality for `dotenv` and AWS Secrets Manager providers. At some point, we would also need full lifecycle support for Vault, which means we can also take care of the implementation 🙂

Cheers!

**Comment by jondot** [comment]
Yes it completely make sense, happy to take a look at the PR
