### ISSUE TITLE
Add support for Azure Vault

### ISSUE THREAD

**Issue by hussainanjar** [SpectralOps/teller#62]

**Comment by svg153** [comment]
I am interested in this provider.

Missing `new-provider` label and [project](https://github.com/orgs/SpectralOps/projects/1/views/1) probably?. I think you are using this to organize work.

Thanks :)

**Comment by lreuven** [comment]
@svg153   Will handle it soon :)

**Comment by kaplanelad** [comment]
Hey @hussainanjar @svg153,
I'll add more documentation to readme.md file soon, but in the meantime, you can do the following steps:

1. Run `teller new ` and select `Azure Key Vault` from Teller wizard
2. Provider authentication: Implement Azure client and use from environment variables in the order:
// 1. Client credentials
// 2. Client certificate
// 3. Username password
// 4. MSI

Then you need to set `KVAULT_NAME` (as environment variable) with the vault name.

Let me know if there is any problem

**Comment by kaplanelad** [comment]
Azure provider now support read / write.
