### ISSUE TITLE
Adding Application Logger 

### ISSUE THREAD

**Issue by kaplanelad** [SpectralOps/teller#71]
We need to add an application logger into our code for:

## Why?
1. Better debugging visibility
2. Gives the user more verbosity on the commands
3. Allow to attache log when users open an issue 

## How:
Implement logger and cover the essential places with the log message

## Note
We need to keep the STDOUT cleanest like we have today. The log will throw to the screen only in errors or when the user asks for with new flag  `--log-level` to any Teller commands.

**Comment by jondot** [comment]
sounds good
- maybe go to STDERR by default for all non-operational logs?
- also, any log lib you prefer?

**Comment by jondot** [comment]
testing..

**Comment by kaplanelad** [comment]
1. sure, this is the idea
2. I have good experience with [logrus](https://github.com/Sirupsen/logrus), very flexible, supports multiple outputs, can extend the logger to multiple entries. Do you have good experience with the different frameworks?

**Comment by jondot** [comment]
Yep, I use logrus when I need colors & such.
Zap when I only need structured logs
