### ISSUE TITLE
README missing default variable for template

### ISSUE THREAD

**Issue by derektamsen** [SpectralOps/teller#8]
The `README.md` is missing the [default parameter variable](https://github.com/SpectralOps/teller/blob/56a0b4d9cc1e3338e37d6ef8f5b888a41b3529e5/pkg/core/types.go#L62) for teller templates rendered with `teller template` and `.Teller.EnvByKey`

```
Error: cannot render template 'connet.tmpl': template: t:1:21: executing "t" at <.Teller.EnvByKey>: wrong number of args for EnvByKey: want 2 got 1
```

**Comment by jondot** [comment]
Great catch! fixed!

**Comment by derektamsen** [comment]
Great! Thanks! I was just going to open a PR.

**Comment by jondot** [comment]
Oh my, I'll try to ask you next time 😄 
Thanks for the keen eye!

**Comment by derektamsen** [comment]
Fixed in https://github.com/SpectralOps/teller/commit/adb7d6794dee2aa599367454d73d20afa4ef0ad3
