### ISSUE TITLE
Add KeyPass provider

### ISSUE THREAD

**Issue by kaplanelad** [SpectralOps/teller#81]
## New Provider Request
Add [KeePass](https://keepass.info/) provider

## Details
- Name: KeePass
- URL: https://keepass.info/
- Modes: (read/write/read+write)
- GitHub projects: https://github.com/tobischo/gokeepasslib, https://github.com/tobischo/gokeepasslib/tree/master/examples

**Comment by kaplanelad** [comment]
Keypass provider was added

**Comment by bakito** [comment]
Is keepass not supported any more?
