### ISSUE TITLE
Add docker secret files support

### ISSUE THREAD

**Issue by nazar256** [SpectralOps/teller#83]
## Details
- Name: secret files
- URL: https://docs.docker.com/engine/swarm/secrets/#how-docker-manages-secrets
- Modes: (read)
- GitHub projects: 
- API Documentation: https://docs.docker.com/engine/swarm/secrets/#how-docker-manages-secrets

For security reasons secrets should be mounted as files inside docker container rather than passed as environment variable. However only few applications support those files. For easy solving this issue it would be great to have a tool which transforms secrets from files into environment variables, but **inside the container**.

**Comment by kaplanelad** [comment]
Hey @nazar256,
Thanks for the idea and the PR! 
Before you make my comments in your PR, please check if the `filesystem` plugin can solve your issue: https://github.com/SpectralOps/teller#filesystem?

**Comment by nazar256** [comment]
Yes, it does solve my problem. Thank you! I'm closing my PR as `filesystem` sounds better for what plugin does (more general).
